### ISSUE TITLE
Query on creating pdf with math equations and symbols

### ISSUE THREAD

**Issue by varunkuntal** [adyavanapalli/Stanford-Introduction-to-Mathematical-Thinking#1]
Hi, 
I wish to write answers to assignments as pdf with all symbols and equations as you did, can you tell how you wrote the solutions, or which software you used. Thanks.

**Comment by adyavanapalli** [comment]
Hi @varununleashed, I used [LyX](https://www.lyx.org/), which provides a convenient IDE to write what is essentially [LaTeX](https://en.wikipedia.org/wiki/LaTeX). Let me know if you have any other questions!
