### ISSUE TITLE
As. 2, ex. A2: possible answer

### ISSUE THREAD

**Issue by Leontopod** [adyavanapalli/Stanford-Introduction-to-Mathematical-Thinking#3]
Let SoPaM be the state of a person after the movie.
"I was not displeased with the movie" implies "but I wasn't pleased either, nor is my impression any more extreme." and is therefore ≡
 ≡ SoPaM<sub>1</sub> **∉** (⋯, **−**PLEASED] ∪ [PLEASED, ⋯) ≡
 ≡ **−**PLEASED < SoPaM<sub>1</sub> < PLEASED
(assuming that PLEASED can be assigned a constant value on a scale, standing at the positive side of a neutral point, and DISPLEASED = **−**PLEASED)

**Comment by adyavanapalli** [comment]
This makes sense. In some way, we have to indicate that "not displeased" ≠ "displeased" i.e. they're not boolean opposites, which you have done by saying that "not displeased" = "not in the set containing displeased and pleased". It seems there are _at least_ three states defined as "pleased", "displeased", and "not displeased" i.e. the "not" in front of the "displeased" isn't actually a negation. I like your approach! Thanks for your comment!

**Comment by Leontopod** [comment]
> This makes sense. In some way, we have to indicate that "not displeased" ≠ "pleased*" i.e. they're not boolean opposites

and just to conclude how inconsistent a natural language can be, think about the statement "I'm not pleased" :P It may mean that one is displeased, while "I'm not displeased" does not suggest by itself that one is pleased. That's just because sometimes we use "not" with a positive adjective to sound more polite and moderate than we would if we used its negative antonym. But conversely we use "not" with a negative adjective when we refrain from extreme positivity about something. 
As a different example, here's a generic scale of wellness:
{-3: "awful", -2: "not good", -1: "not very well", 0: "fine", 1: "not bad", 2: "very well", 3: "awesome"}
:-)
And big thanks to you for compiling the answers! It's greatly helpful to be able to check out someone else's take despite working alone.

**Comment by adyavanapalli** [comment]
Exactly!

> And big thanks to you for compiling the answers! It's greatly helpful to be able to check out someone else's take despite working alone.

You're very welcome 😄 !
