### ISSUE TITLE
A10.1, problem 2 (b) is incorrect

### ISSUE THREAD

**Issue by daltonlight** [adyavanapalli/Stanford-Introduction-to-Mathematical-Thinking#4]
The correct solution is (-oo,1] U (7,oo).
The posted (incorrect) solution is (-oo,1) U [7,oo).

**Comment by adyavanapalli** [comment]
You're absolutely right. I'll fix that in a bit. Good catch 😄!

**Comment by adyavanapalli** [comment]
Just pushed a change.
88a068c6a8ec213a5c7af4f2ff35eef77ed4079d

Thanks for your help!
